spring.application.name=enterprise-procurement-system

# JDBC Database Connection Configuration
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/procurement_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=@2547$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations (Automatically builds tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# ==================================
# SMTP Email Configuration (Gmail)
# ==================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manasaraju1306@gmail.com
spring.mail.password=ijhd gwme gsad fzgs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.connectiontimeout=5000
spring.mail.properties.mail.timeout=5000
spring.mail.properties.mail.writetimeout=5000

# Admin Notification Configuration
app.admin.email=divyashreeraju21@gmail.com

# Error Handling Configuration
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never

# ==================================
# SUPPLIER CREDENTIAL MAPPINGS (Reference / Environment Constants)
# ==================================
supplier.dell.email=sales@delldirect.com
supplier.dell.password=DellSecure@2026#

supplier.apple.email=enterprise@apple.com
supplier.apple.password=AppleEnterprise!99

supplier.techdist.email=contact@techdist.com
supplier.techdist.password=TechDistPass$88

supplier.globalsoftware.email=orders@globalsoftware.com
supplier.globalsoftware.password=GlobalSoft#Order44

supplier.comfortseats.email=sales@comfortseats.com
supplier.comfortseats.password=ComfortSeats_2026!

supplier.onboarding.email=support@onboardingsuppliers.com
supplier.onboarding.password=OnboardSupport$55